### ISSUE TITLE
SyntaxError: a.rb:3: class/module name must be CONSTANT

### ISSUE THREAD

**Issue by reversi-fun** [kiuKisas/th_prim_queue#1]
name of class to be Th_prim_queue.

**Comment by reversi-fun** [comment]
Performance is good of Th_prim_queue.

["FastContainers::PriorityQueue", 0.15625]<---  not thread-safe
["thread-safe Queue", 0.15625] <--- not priorityed
["priority_queue", 0.21875] <---- not thread-safe
["Th_prim_queue", 0.890625] <----!! good because thread-safe and priorityed !!
["real ruby queue", 1.296875] <---- not thread-safe
["native sort queue", 13.317382]<---- not thread-safe
["pqueue", 28.010743]<---- not thread-safe


"real ruby queue" and "native sort queue" is follows.
 http://www.brianstorti.com/implementing-a-priority-queue-in-ruby/

"pqueue" is follows
 https://github.com/rubyworks/pqueue

**Comment by kinooyume** [comment]
Interesting, what benchmark did you use ?
